Delivery.Web/Models/InvoiceViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Delivery.Web.Models
{
    /// <summary>
    /// Shipment ViewModel
    /// </summary>
    public class InvoiceViewModel
    {
        /// <summary>
        /// Shipment Id
        /// </summary>
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Shipment number
        /// </summary>
        [Required]
        [Display(Name = "Номер відправлення")]
        [StringLength(30, ErrorMessage = "Максимальна довжина номера - 30 символів")]
        [MinLength(6, ErrorMessage = "Мінімальна довжина номера - 6 символів")]
        public string Number { get; set; }

        /// <summary>
        /// Postal operator name
        /// </summary>
        [Required(ErrorMessage = "Не вказано поштового оператора")]
        [Display(Name = "Поштовий оператор")]
        public string PostOperatorName { get; set; }

        /// <summary>
        /// Date of sending according to the information system of the postal operator
        /// </summary>
        [Required]
        [Display(Name = "Дата відправлення")]
        public DateTime SendDateTime { get; set; }

        /// <summary>
        /// The address of the current location of shipment
        /// </summary>
        [Display(Name = "Місцезнаходження")]
        [StringLength(30, ErrorMessage = "Максимальна довжина адреси місцезнаходження - 300 символів")]
        public string CurrentLocation { get; set; }

        /// <summary>
        /// Current shipment status
        /// </summary>
        [Display(Name = "Статус")]
        [StringLength(30, ErrorMessage = "Максимальна довжина статусу відправлення - 300 символів")]
        public string ActualStatus { get; set; }

        /// <summary>
        /// Notes
        /// </summary>
        [Display(Name = "Коментар")]
        [StringLength(30, ErrorMessage = "Максимальна довжина коментаря - 300 символів")]
        public string Notes { get; set; }
    }
}

Delivery.Web/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Delivery.Web.Models
{
    /// <summary>
    /// Login ViewModel
    /// </summary>
    public class LoginViewModel
    {
        /// <summary>
        /// User email
        /// </summary>
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        /// <summary>
        /// User password
        /// </summary>
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        /// <summary>
        /// Shows whether to save local log data
        /// </summary>
        [Display(Name = "Запам'ятати мене?")]
        public bool RememberMe { get; set; }
    }
}

Delivery.Web/Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Delivery.Web.Models
{
    /// <summary>
    /// ViewModel user registration
    /// </summary>
    public class RegisterViewModel
    {
        /// <summary>
        /// User email
        /// </summary>
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// User password
        /// </summary>
        [Required]
        [StringLength(100, ErrorMessage = "Пароль повинен містити не менше 6 символів.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        /// <summary>
        /// Confirm user password
        /// </summary>
        [DataType(DataType.Password)]
        [Display(Name = "Підтвердіть пароль")]
        [Compare("Password", ErrorMessage = "Пароль і підтвердження не співпадають.")]
        public string ConfirmPassword { get; set; }

    }
}

Delivery.Web/Controllers/InvoicesController.cs
using Delivery.BLL.Services;
using Delivery.Web.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Delivery.Web.Controllers
{
    /// <summary>
    /// Shipment controller
    /// </summary>
    [Authorize]
    public class InvoicesController : BaseController
    {
        private readonly IInvoicesService _invoicesService;

        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="invoicesService">Object of the Invoices service</param>
        public InvoicesController(IInvoicesService invoicesService)
        {
            _invoicesService = invoicesService;
        }

        /// <summary>
        /// Returns page for create a new shipment
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }

        /// <summary>
        /// Gets the number from the page of creation of the shipment, checks in the list of existing, searches for new in information systems of postal operators and saves in a DB
        /// </summary>
        /// <param name="model">SearchInvoiceViewModel</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SearchInvoiceViewModel model)
        {
            if (ModelState.IsValid)
            {
                _invoicesService.Add(User.Identity.GetUserId(), model.Number);

                return RedirectToAction("Index");
            }

            return View("Create");
        }

        /// <summary>
        /// Returns a page to confirm the deletion of the shipment
        /// </summary>
        /// <param name="id">Shipment Id</param>
        /// <returns>Page to confirm the deletion of the shipment</returns>
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null) throw new Exception("Не обрано відправлення для видалення.");

            var invoiceDto = _invoicesService.GetById((int)id);

            if (invoiceDto == null) throw new Exception("Відправлення не знайдено.");

            return View("Delete", Mapper.Map<InvoiceViewModel>(invoiceDto));
        }

        /// <summary>
        /// Deletes the shipment from the db
        /// </summary>
        /// <param name="id">Shipment Id</param>
        /// <param name="invoice">View model of the shipment</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(int id, InvoiceViewModel invoice)
        {
            _invoicesService.Remove(id);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Shipment details
        /// </summary>
        /// <param name="id">Shipment Id</param>
        /// <returns>Page of the shipment info</returns>
        [HttpGet]
        public ActionResult Details(int id)
        {
            var invoiceDto = _invoicesService.GetById(id);

            if (invoiceDto == null) throw new Exception("Відправлення не знайдено.");

            return View("Details", Mapper.Map<InvoiceViewModel>(invoiceDto));
        }

        /// <summary>
        /// Returns page with list of user's shipments
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();

            return View("Index", Mapper.Map<List<InvoiceViewModel>>(_invoicesService.GetInvoicesByUserId(userId)));
        }

        /// <summary>
        /// Updates shipment status
        /// </summary>
        /// <param name="id">Shipment Id</param>
        /// <returns>Redirects to page of the shipment info</returns>
        [HttpPost]
        public ActionResult UpdateStatus(int id)
        {
            var invoiceDto = _invoicesService.GetById(id);

            if (invoiceDto == null) throw new Exception("Відправлення не знайдено.");

            _invoicesService.UpdateStatusAsync(id);

            return RedirectToAction("Details", id);
        }
    }
}

Delivery.Web/Controllers/PostOperatorController.cs
using Delivery.BLL.DTO;
using Delivery.BLL.Services;
using Delivery.Web.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Delivery.Web.Controllers
{
    /// <summary>
    /// PostOperators controller
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class PostOperatorController : BaseController
    {
        private readonly IPostOperatorService _postOperatorService;

        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="postOperatorService">Object of the PostOperators service</param>
        public PostOperatorController(IPostOperatorService postOperatorService)
        {
            _postOperatorService = postOperatorService;
        }

        /// <summary>
        /// Returns page for creating the new PostOperator
        /// </summary>
        /// <returns>Page for creating the new PostOperator</returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }

        /// <summary>
        /// Creates the new PostOperator
        /// </summary>
        /// <param name="postOperator">ViewModel of the PostOperator</param>
        /// <returns>View for creating of the PostOperator</returns>
        [HttpPost]
        public ActionResult Create(PostOperatorViewModel postOperator)
        {
            if (ModelState.IsValid)
            {
                _postOperatorService.Add(Mapper.Map<PostOperatorDto>(postOperator));

                return RedirectToAction("Index");
            }

            return View("Create", postOperator);
        }

        /// <summary>
        /// Returns page for edit PostOperator. Admin can edit only status.
        /// </summary>
        /// <param name="id">PostOperator's Id</param>
        /// <returns>View Edit</returns>
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null) throw new Exception("Не обрано поштового оператора для оновлення активності.");

            var postOperatorDto = _postOperatorService.GetById((int)id);

            if (postOperatorDto == null) throw new Exception("Поштового оператора не знайдено.");

            return View("Edit", Mapper.Map<PostOperatorViewModel>(postOperatorDto));
        }

        /// <summary>
        /// Saves edited data to database
        /// </summary>
        /// <param name="postOperator">ViewModel of the PostOperator</param>
        /// <returns>redirect to Index-page</returns>
        [HttpPost]
        public ActionResult Edit(PostOperatorViewModel postOperator)
        {
            if (ModelState.IsValid)
            {
                _postOperatorService.UpdatePostOperator(Mapper.Map<PostOperatorDto>(postOperator));

                return RedirectToAction("Index");
            }

            return View("Edit", postOperator);
        }

        /// <summary>
        /// Returns page with the list of PostOperators
        /// </summary>
        /// <returns>page with the list of PostOperators</returns>
        public ActionResult Index()
        {
            return View("Index", Mapper.Map<List<PostOperatorViewModel>>(_postOperatorService.GetAll()));
        }
    }
}

Delivery.Web/Views/Admin/ConfirmEmail.cshtml
@{
    ViewBag.Title = "Підтвердження Email";
}

<h2>@ViewBag.Title.</h2>
<div>
    <p>
        Дякуємо за пітвердження вашого email. Будь ласка, @Html.ActionLink("натисніть тут для входу", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
    </p>
</div>

Delivery.Web/Views/Admin/DeleteUser.cshtml
@model Delivery.Web.Models.AppUserViewModel

@{
    ViewBag.Title = "Видалення користувача";
}

<h2>Видалення користувача</h2>

<h3>Ви впевнені, що бажаєте видалити запис?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.UserName)</dt>
        <dd>@Html.DisplayFor(model => model.UserName)</dd>
        <dt>@Html.DisplayNameFor(model => model.Email)</dt>
        <dd>@Html.DisplayFor(model => model.Email)</dd>
        <dt>@Html.DisplayNameFor(model => model.Password)</dt>
        <dd>@Html.DisplayFor(model => model.Password)</dd>
        <dt>@Html.DisplayNameFor(model => model.Role)</dt>
        <dd>@Html.DisplayFor(model => model.Role)</dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Видалити" class="btn btn-danger" /> |
            @Html.ActionLink("Назад до списку", "Users")
        </div>
    }
</div>

Delivery.Web/Views/Admin/ForgotPassword.cshtml
@model Delivery.Web.Models.ForgotPasswordViewModel
@{
    ViewBag.Title = "Забули пароль?";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("ForgotPassword", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Введіть Ваш email.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Email посилання" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Delivery.Web/Views/Admin/ForgotPasswordConfirmation.cshtml
@{
    ViewBag.Title = "Підтвердження зміни забутого паролю";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>
<div>
    <p>
        Перевірте свою електронну пошту для зміни паролю.
    </p>
</div>
	

Delivery.Web/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Головна";
}

<h2>Адміністрування</h2>

<div class="row">
    <p>@Html.ActionLink("Користувачі", "Users")</p>
    <p>@Html.ActionLink("Відправлення", "Invoices")</p>
    <p>@Html.ActionLink("Поштові оператори", "Index", "PostOperator")</p>
</div>

Delivery.Web/Views/Admin/Invoices.cshtml
@model IEnumerable<Delivery.Web.Models.InvoiceViewModel>

@{
    ViewBag.Title = "Відправлення";
}

<h2>Відправлення</h2>

<table class="table">
    <tr>
        <th>Оператор</th><th>Номер</th><th>Дата</th><th>Місцезнаходження</th><th>Статус</th><th>Опис</th><th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.PostOperatorName)</td>
        <td>@Html.DisplayFor(modelItem => item.Number)</td>
        <td>@Html.DisplayFor(modelItem => item.SendDateTime)</td>
        <td>@Html.DisplayFor(modelItem => item.CurrentLocation)</td>
        <td>@Html.DisplayFor(modelItem => item.ActualStatus)</td>
        <td>@Html.DisplayFor(modelItem => item.Notes)</td>
        <td>
            @Html.ActionLink("Інфо", "Details", "Invoices", new { id=item.Id }, new { @class = "btn btn-info" }) |
            @Html.ActionLink("Видалити", "Delete", "Invoices", new { id=item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

Delivery.Web/Views/Admin/Login.cshtml
@using Delivery.Web.Models
@model LoginViewModel
@{
    ViewBag.Title = "Увійти";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Admin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Використовуйте обліковий запис для входу.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Увійти" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Реєстрація нового користувача", "Register")
                </p>
            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Delivery.Web/Views/Admin/Register.cshtml
@model Delivery.Web.Models.RegisterViewModel
@{
    ViewBag.Title = "Реєстрація";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Register", "Admin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Створити новий обліковий запис.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Зареєструвати" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Delivery.Web/Views/Admin/UserDetails.cshtml
@model Delivery.Web.Models.AppUserViewModel

@{
    ViewBag.Title = "Інформація про користувача";
}

<h2>Інформація про користувача</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.UserName)</dt>
        <dd>@Html.DisplayFor(model => model.UserName)</dd>
        <dt>@Html.DisplayNameFor(model => model.Email)</dt>
        <dd>@Html.DisplayFor(model => model.Email)</dd>
        <dt>@Html.DisplayNameFor(model => model.Password)</dt>
        <dd>@Html.DisplayFor(model => model.Password)</dd>
        <dt>@Html.DisplayNameFor(model => model.Role)</dt>
        <dd>@Html.DisplayFor(model => model.Role)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Назвад до списку", "Users")
</p>

Delivery.Web/Views/Admin/Users.cshtml
@model IEnumerable<Delivery.Web.Models.AppUserViewModel>

@{
    ViewBag.Title = "Користувачі";
}

<h2>Користувачі</h2>

<table class="table">
    <tr>
        <th>Ім'я користувача</th><th>Email</th><th>Пароль</th><th>Роль</th><th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.UserName)</td>
        <td>@Html.DisplayFor(modelItem => item.Email)</td>
        <td>@Html.DisplayFor(modelItem => item.Password)</td>
        <td>@Html.DisplayFor(modelItem => item.Role)</td>
        <td>
            @Html.ActionLink("Details", "UserDetails", new { id=item.Id }) |
            @Html.ActionLink("Delete", "DeleteUser", new { id=item.Id })
        </td>
    </tr>
}

</table>